Feature/clases
Victordf2005/PRIAP0 pull request #1
Opened 2023-01-17 19:39 UTC by Victordf2005

Esto es una revisión de prueba

2023-01-17 19:43 UTC, 9RACHA approved these changes
Todo correcto

2023-01-17 19:45 UTC, SoniaPria approved these changes

2023-01-17 19:50 UTC, noevilamunoz requested changes
**Problema** Non compila, parece que falta o main

2023-01-18 10:09 UTC, noevilamunoz commented
Segue sen compilar, adxúntovos o código de erro que aparece.
`error CS5001: Program does not contain a static 'Main' method suitable for an entry point`

2023-01-18 10:11 UTC, noevilamunoz commented
Por outro lado estades intentando facer un merge da rama `feature/clases` contra a rama `main`
É necesario cambiar isto, imos intentar traballar sempre contra a rama `develop` polo que a rama contra a que hai que mergear `feature/clases` é `develop`

2023-01-19 19:47 UTC, noevilamunoz requested changes

2023-01-19 19:47 UTC, noevilamunoz commented on Main.cs
> +            (int)TipoPersonaje.Arquero;
**Error:** No compila por culpa de esta línea, recordad que no soy un compilador, si hay un problema hay que ver qué pasa y por qué no compila, este es simplemente porque sobra el punto y coma.

2023-01-19 19:47 UTC, noevilamunoz commented on Main.cs
> +enum TipoPersonaje {
Un enumerado aquí solo trae problemas ya que no se está utilizando de la manera correcta y hay que hacer "ñapas" como los castings que estáis haciendo, que son un mal hábito de programación ya que son fuentes de bugs. Si queréis mantener una estructura similar deberíais utilizar un diccionario, aunque me parece un poco de sobreingeniería para la necesidad que tenemos aquí.

2023-01-19 21:00 UTC, noevilamunoz approved these changes

2023-01-19 21:01 UTC, merged